### ISSUE TITLE
ur’strings’ are a syntax error in Python 3

### ISSUE THREAD

**Issue by cclauss** [vstinner/unicode_book#23]
In Python 3, you can have u’strings’ or r’strings’ but ur’strings’ are not allowed.

flake8 testing of https://github.com/vstinner/unicode_book on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./build_latex.py:48:32: E999 SyntaxError: invalid syntax
    ur"\begin{DUlineblock}{0em}",
                               ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by vstinner** [comment]
The commit faffafb7d63a229a41ab55f1ac91b207415920b4 should fix the syntax error on Python 3.
