### ISSUE TITLE
JS or JSON issues with Unicode

### ISSUE THREAD

**Issue by SheilaRT** [vstinner/unicode_book#24]
This book does not address JS or JSON issues with Unicode at all. Instead it's dealt with rather flippantly by stating other languages aren't important after listing a small handful of programming language and three variants of MySQL. While the author may not like JS or using JSON as a database, the fact of the matter is that they are used by much of the coding community. Leaving them out (along with mentions of other languages, eg Haskell) is a disservice to large swaths of the community.

**Comment by vstinner** [comment]
I decided to give my ebook for free in 2010. I wrote on languages and technologies I care about.
