### ISSUE TITLE
Fix rst list: lacks a newline and two whitespaces (12.1 MySQL UTF-8 variants)

### ISSUE THREAD

**Issue by openandclose** [vstinner/unicode_book#25]
Thank you for publishing a super-easy to read unicode book.

---

https://github.com/vstinner/unicode_book/blob/master/database_systems.rst

From:

```
MySQL supports two UTF-8 variants:
* utf8mb4: This is the full UTF-8 character set supported since MySQL 5.5
* utf8: Also known as utf8mb3. This only supports the Basic Multilingual Plane of
Unicode 3.0 and doesn't support 4-byte characters.
```

To:

```
MySQL supports two UTF-8 variants:

* utf8mb4: This is the full UTF-8 character set supported since MySQL 5.5.
* utf8: Also known as utf8mb3. This only supports the Basic Multilingual Plane of
  Unicode 3.0 and doesn't support 4-byte characters.
```

**Comment by vstinner** [comment]
Should be fixed by:

```
commit 15b520ff4cbf9f71e7ee008eeaa3d09a9d8ac2c8 (HEAD -> master, origin/master, origin/HEAD)
Author: Victor Stinner <vstinner@python.org>
Date:   Mon Sep 23 14:07:47 2019 +0200

    Add newline
```

**Comment by openandclose** [comment]
* You perhaps need two whitespaces before 'Unicode 3.0'
(to make it **rst** list).

* Also the readthedocs site is not updated (from 1 year ago).
maybe [this](https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services)?

**Comment by vstinner** [comment]
> Also the readthedocs site is not updated (from 1 year ago). maybe this?

Right, I had to remove the Webhook and use the new integration thing from ReadTheDocs.

> You perhaps need two whitespaces before 'Unicode 3.0' (to make it rst list).

Pushed and the fix triggered a new build ;-)
