### ISSUE TITLE
Maybe Кракозябры is missing in the pdf version at https://readthedocs.org/projects/unicodebook/downloads/pdf/latest/

### ISSUE THREAD

**Issue by alessandro-gentilini** [vstinner/unicode_book#26]
Hello, maybe this is not an issue for https://github.com/vstinner/unicode_book/ but it is an issue for `rst2pdf`, anyway the Кракозябры is missing from the pdf at https://readthedocs.org/projects/unicodebook/downloads/pdf/latest/ as you can see in the following screenshot

![image](https://user-images.githubusercontent.com/2438459/81670817-759cfc00-9448-11ea-8e47-fcfcc5cb7ff4.png)

Or is it a problem with my pdf reader?

**Comment by vstinner** [comment]
I had hard time to build a PDF in the past. Now, it's built by ReadTheDocs. I don't have much skills in LaTeX. Do you know how to fix the issue?

**Comment by alessandro-gentilini** [comment]
@vstinner Do you confirm that the pdf has the problem? In the pdf Русский is missing too.

The html https://unicodebook.readthedocs.io/definitions.html#mojibake is fine.

I have no idea on how to fix the issue, at least the pdf as it is rendered by my reader does not exhibit an unintentional mojibake 😄 but just some omissions.

Why are you talking about LaTeX, according to https://github.com/vstinner/unicode_book/blob/master/README.rst the rst to pdf does not involve LaTeX.

**Comment by vstinner** [comment]
I understood that the PDF rendering involves LaTeX.

**Comment by alessandro-gentilini** [comment]
@vstinner OK, I submit this issue because I found your book really useful and it's a pity the pdf is missing some texts in Cyrillic. No problem for me if you close this issue. Thank you.
