### ISSUE TITLE
Confusion around the definition of "length" in a character string

### ISSUE THREAD

**Issue by jsamr** [vstinner/unicode_book#27]
Perhaps it is all my misunderstanding, but this statement:

> The length of a character string implemented using UTF-16 is the number of UTF-16 units, and not the number of characters, which is confusing.

... seems very arbitrary (language-dependent?). Did I miss something?

I like how http://utf8everywhere.org/ reflects on the notion of "length" in [Myth: Counting coded characters or code points is important.](http://utf8everywhere.org/#myth.strlen)

>  The number of code points in [a character string] is irrelevant to almost any software engineering task, with perhaps the only exception of converting the string to UTF-32. For example:
>
> - For cursor movement, text selection and alike, grapheme clusters shall be used.
> - For limiting the length of a string in input fields, file formats, protocols, or databases, the length is measured in code units of some predetermined encoding. The reason is that any length limit is derived from the fixed amount of memory allocated for the string at a lower level, be it in memory, disk or in a particular data structure.
> - The size of the string as it appears on the screen is unrelated to the number of code points in the string. One has to communicate with the rendering engine for this. Code points do not occupy one column even in monospace fonts and terminals. POSIX takes this into account. 

Sibling myth: [The string length() operation must count user-perceived or coded characters. If not, it does not support Unicode properly.](http://utf8everywhere.org/#myth.strlen.correctness)

**Comment by jsamr** [comment]
I misread; the definition is accurate! Sorry for the false flag.

**Comment by vstinner** [comment]
> I misread; the definition is accurate! Sorry for the false flag.

Oh, don't worry. Unicode is hard, it takes time to get used to it.
