### ISSUE TITLE
int isUTF8 return 1 for 100% ascii text

### ISSUE THREAD

**Issue by zigm** [vstinner/unicode_book#31]
Looking for clarification why int isUTF8(const char *data, size_t size) return 1 when text is 100% ascii, i.e all characters are  < 0x7f.

Ok, I suppose I should call isASCII first. ASCII characters are valid UTF8 characters are suppose.

**Comment by zigm** [comment]
Resolved, closing.

**Comment by vstinner** [comment]
UTF-8 is a superset of ASCII. ASCII can be decoded by UTF-8.

**Comment by zigm** [comment]
Thanks for clarification. And thanks for great online documentations and online book covering UNICODE issues.

**Comment by vstinner** [comment]
You're welcome.
